const { USER_ROLES } = require('../shared/enums');

const PERMISSIONS = {
  MANAGE_USERS: 'manage_users',
  MANAGE_DEPARTMENTS: 'manage_departments',
  MANAGE_ROOMS: 'manage_rooms',
  MANAGE_BEDS: 'manage_beds',
  MANAGE_DRUGS: 'manage_drugs',
  VIEW_REPORTS: 'view_reports',
  ACCESS_RECEPTION: 'access_reception',
  ACCESS_EMR: 'access_emr',
  ACCESS_LAB: 'access_lab',
  ACCESS_PHARMACY: 'access_pharmacy',
  ACCESS_BILLING: 'access_billing',
};

const ROLES_PERMISSIONS = {
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_DEPARTMENTS,
    PERMISSIONS.MANAGE_ROOMS,
    PERMISSIONS.MANAGE_BEDS,
    PERMISSIONS.MANAGE_DRUGS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [USER_ROLES.LEADER]: [PERMISSIONS.VIEW_REPORTS],
  [USER_ROLES.RECEPTIONIST]: [PERMISSIONS.ACCESS_RECEPTION],
  [USER_ROLES.DOCTOR]: [PERMISSIONS.ACCESS_EMR],
  [USER_ROLES.NURSE]: [PERMISSIONS.ACCESS_EMR],
  [USER_ROLES.LAB_TECHNICIAN]: [PERMISSIONS.ACCESS_LAB],
  [USER_ROLES.PHARMACIST]: [PERMISSIONS.ACCESS_PHARMACY],
  [USER_ROLES.CASHIER]: [PERMISSIONS.ACCESS_BILLING],
};

module.exports = {
  PERMISSIONS,
  ROLES_PERMISSIONS,
};